### ISSUE TITLE
Chrome version: marked with warning "may soon no longer be supported"

### ISSUE THREAD

**Issue by DmytroRekechynskyOSF** [ForkPoint/dwithease#16]
Hello, guys!
First of all, thanks a lot for the precious time-saving extension 🤝

Unfortunately, Chrome Web Store left the warning in the description:

> This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

I'm afraid that after some time Chrome will disable the extension automatically, so it means the "best practices" from Google should be applied to save it

**Comment by krisforkpoint** [comment]
Hello @DmytroRekechynskyOSF,

Thank you for opening this issue!

Our team is aware of this warning, however, we believe it might be a bit misleading because we are following the "best coding practices". Google is forcing all existing V2 extensions to migrate to the new [Manifest V3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3), which is the actual reason for the warning.

We've been working on the update to Manifest V3 for quite some time, and we'll be releasing it in the upcoming weeks.

Best Regards,
\- Chris

**Comment by DmytroRekechynskyOSF** [comment]
Hello again:)
I see the new release fixed the issue, congrats! Since it's resolved, I close the issue
